spring:
  application:
    name: resource_management_system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resourcedb
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  web:
    resources:
      static-locations: classpath:/static/
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: edu.just.resource_management_system.pojo

